#Python and Data Science Drilling Machine Project

*   Name - Murari Sen 
*   email- murarisen8878@gmailcom

# Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import copy
# import matplotlib.pyplot as plt
# import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import pickle

# Import the dataset

In [3]:
df=pd.read_csv("Drillingdata.csv")
df1=df
df

,Flushing,Discharge,Pulse,Duty,Circularity,Recast
0,20,4,8,50,0.878,13.90
1,25,2,8,50,0.972,12.60
2,25,6,6,60,0.897,14.11
3,25,4,10,70,0.908,12.09
4,30,4,10,60,0.953,13.12
5,30,4,8,50,0.986,11.17
6,25,2,10,60,0.909,10.91
7,20,4,10,60,0.902,12.95
8,20,6,8,60,0.898,12.76
9,25,2,8,70,0.889,8.64
10,20,4,8,70,0.931,9.13
11,25,6,8,70,0.893,10.19
12,25,6,8,50,0.954,8.20
13,20,4,8,50,0.878,13.90
14,25,4,8,60,0.915,7.89
15,25,4,8,60,0.925,8.12
16,25,4,10,50,0.945,13.16
17,20,4,6,60,0.938,7.50
18,30,6,8,60,0.959,9.36
19,25,4,8,60,0.911,7.96
20,20,2,8,60,0.946,6.12
21,25,6,10,60,0.959,9.89
22,25,4,6,50,0.981,13.41
23,30,4,6,60,0.956,16.56
24,30,4,8,70,0.885,14.35
25,30,2,8,60,0.902,13.06
26,25,4,6,70,0.911,7.39
27,25,2,6,60,0.951,8.34
28,25,4,8,60,0.922,7.72
29,25,4,8,60,0.913,8.10

In [5]:
# from google.colab import drive
# drive.mount('/content/drive')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0    Flushing              30 non-null     int64
 1    Discharge             30 non-null     int64
 2   Pulse                  30 non-null     int64
 3    Duty                  30 non-null     int64
 4   Circularity            30 non-null     float64
 5    Recast                30 non-null     float64
dtypes: float64(2), int64(4)
memory usage: 1.5 KB

In [7]:
df.shape

(30, 6)

In [56]:
df.describe()

,Flushing,Discharge,Pulse,Duty,Circularity,Recast
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,24.833333,4.000000,8.000000,59.666667,0.925567,10.753333
std,3.343376,1.286535,1.286535,6.686751,0.030948,2.758889
min,20.000000,2.000000,6.000000,50.000000,0.878000,6.120000
25%,25.000000,4.000000,8.000000,60.000000,0.902000,8.140000
50%,25.000000,4.000000,8.000000,60.000000,0.918500,10.550000
75%,25.000000,4.000000,8.000000,60.000000,0.952500,13.105000
max,30.000000,6.000000,10.000000,70.000000,0.986000,16.560000

In [33]:
df.isnull().sum()

 Flushing                0
 Discharge               0
Pulse                    0
 Duty                    0
Circularity              0
 Recast                  0
dtype: int64

In [69]:
#X1=df[' Recast  ']

In [10]:
from pandas._libs.hashtable import value_count
#df['furnishingstatus'].value_counts()

# Changing the Categorical data to Binary Data (yes=1,no=0)

In [11]:
#df=df.replace({'mainroad': {'yes': 1,'no': 0}})

In [37]:
#df=df.replace({'basement': {'yes': 1,'no': 0}})
#df=df.replace({'guestroom': {'yes': 1,'no': 0}})
#df=df.replace({'hotwaterheating': {'yes': 1,'no': 0}})
#df=df.replace({'airconditioning': {'yes': 1,'no': 0}})
#df=df.replace({'prefarea': {'yes': 1,'no': 0}})

In [12]:
df

,Flushing,Discharge,Pulse,Duty,Circularity,Recast
0,20,4,8,50,0.878,13.90
1,25,2,8,50,0.972,12.60
2,25,6,6,60,0.897,14.11
3,25,4,10,70,0.908,12.09
4,30,4,10,60,0.953,13.12
5,30,4,8,50,0.986,11.17
6,25,2,10,60,0.909,10.91
7,20,4,10,60,0.902,12.95
8,20,6,8,60,0.898,12.76
9,25,2,8,70,0.889,8.64
10,20,4,8,70,0.931,9.13
11,25,6,8,70,0.893,10.19
12,25,6,8,50,0.954,8.20
13,20,4,8,50,0.878,13.90
14,25,4,8,60,0.915,7.89
15,25,4,8,60,0.925,8.12
16,25,4,10,50,0.945,13.16
17,20,4,6,60,0.938,7.50
18,30,6,8,60,0.959,9.36
19,25,4,8,60,0.911,7.96
20,20,2,8,60,0.946,6.12
21,25,6,10,60,0.959,9.89
22,25,4,6,50,0.981,13.41
23,30,4,6,60,0.956,16.56
24,30,4,8,70,0.885,14.35
25,30,2,8,60,0.902,13.06
26,25,4,6,70,0.911,7.39
27,25,2,6,60,0.951,8.34
28,25,4,8,60,0.922,7.72
29,25,4,8,60,0.913,8.10

# Use of One hot Encoding to convert to make numeric/binary data

In [13]:
#df=pd.get_dummies(df,columns=['furnishingstatus'])

In [14]:
df

,Flushing,Discharge,Pulse,Duty,Circularity,Recast
0,20,4,8,50,0.878,13.90
1,25,2,8,50,0.972,12.60
2,25,6,6,60,0.897,14.11
3,25,4,10,70,0.908,12.09
4,30,4,10,60,0.953,13.12
5,30,4,8,50,0.986,11.17
6,25,2,10,60,0.909,10.91
7,20,4,10,60,0.902,12.95
8,20,6,8,60,0.898,12.76
9,25,2,8,70,0.889,8.64
10,20,4,8,70,0.931,9.13
11,25,6,8,70,0.893,10.19
12,25,6,8,50,0.954,8.20
13,20,4,8,50,0.878,13.90
14,25,4,8,60,0.915,7.89
15,25,4,8,60,0.925,8.12
16,25,4,10,50,0.945,13.16
17,20,4,6,60,0.938,7.50
18,30,6,8,60,0.959,9.36
19,25,4,8,60,0.911,7.96
20,20,2,8,60,0.946,6.12
21,25,6,10,60,0.959,9.89
22,25,4,6,50,0.981,13.41
23,30,4,6,60,0.956,16.56
24,30,4,8,70,0.885,14.35
25,30,2,8,60,0.902,13.06
26,25,4,6,70,0.911,7.39
27,25,2,6,60,0.951,8.34
28,25,4,8,60,0.922,7.72
29,25,4,8,60,0.913,8.10

In [29]:
#data1=copy.deepcopy(df)

# Assigning Data to independent variable(X) and dependent variable(y)

In [15]:
X=df.drop("Circularity",axis=1)
y=df["Circularity"]

In [16]:
df

,Flushing,Discharge,Pulse,Duty,Circularity,Recast
0,20,4,8,50,0.878,13.90
1,25,2,8,50,0.972,12.60
2,25,6,6,60,0.897,14.11
3,25,4,10,70,0.908,12.09
4,30,4,10,60,0.953,13.12
5,30,4,8,50,0.986,11.17
6,25,2,10,60,0.909,10.91
7,20,4,10,60,0.902,12.95
8,20,6,8,60,0.898,12.76
9,25,2,8,70,0.889,8.64
10,20,4,8,70,0.931,9.13
11,25,6,8,70,0.893,10.19
12,25,6,8,50,0.954,8.20
13,20,4,8,50,0.878,13.90
14,25,4,8,60,0.915,7.89
15,25,4,8,60,0.925,8.12
16,25,4,10,50,0.945,13.16
17,20,4,6,60,0.938,7.50
18,30,6,8,60,0.959,9.36
19,25,4,8,60,0.911,7.96
20,20,2,8,60,0.946,6.12
21,25,6,10,60,0.959,9.89
22,25,4,6,50,0.981,13.41
23,30,4,6,60,0.956,16.56
24,30,4,8,70,0.885,14.35
25,30,2,8,60,0.902,13.06
26,25,4,6,70,0.911,7.39
27,25,2,6,60,0.951,8.34
28,25,4,8,60,0.922,7.72
29,25,4,8,60,0.913,8.10

In [74]:
# X1=df1.drop("Recast")
#y1=df1["Recast"]
#y1

In [17]:
print(X.shape)
print(y.shape)

(30, 5)
(30,)

Spliting the dataset into Training and Testing Data

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)

In [27]:
X_train.head()

,Flushing,Discharge,Pulse,Duty,Recast
17,20,4,6,60,7.50
29,25,4,8,60,8.10
19,25,4,8,60,7.96
0,20,4,8,50,13.90
3,25,4,10,70,12.09

#Using the Linear Regression  to Train the Model

In [28]:
model=LinearRegression()

In [29]:
model.fit(X_train,y_train)

LinearRegression()

In [30]:
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred

array([0.89945156, 0.91708652, 0.9346721 , 0.93349609, 0.9180829 ,
       0.94838181])

In [31]:
y_test

11    0.893
21    0.959
28    0.922
15    0.925
20    0.946
25    0.902
Name: Circularity, dtype: float64

In [32]:
r2_score(y_test, y_pred)

-0.5714219040972628

In [25]:
# model.intercept_

In [51]:
# arr=np.array([])

li=[29,	25,	4,	8,	60]

model.predict([li])

c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.89721793])

In [52]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)